n = input('Enter something: ')
print(type(n))
print('Is it a number?', n.isnumeric())
print('Is it alphabetic?', n.isalpha())
print('Is it alphanumeric?', n.isalnum())
print('Is it in uppercase?', n.isupper())
print('Is it in lowercase?', n.islower())
print('Is it a space?', n.isspace())
print('Is it capitalized?', n.istitle())